name: prueba CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  hola_mundo:
    runs-on: ubuntu-latest
    steps:
      - name: saludar
        run: echo "Hola, Mundo"
       